name: nfc_manager
description: Flutter plugin for accessing the NFC features on Android and iOS.
version: 3.5.1
homepage: https://github.com/okadan/flutter-nfc-manager

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.nfcmanager
        pluginClass: NfcManagerPlugin
      ios:
        pluginClass: NfcManagerPlugin
